kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    kubelet:
      tlsVerify: false
    site: "datadoghq.eu"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    clusterName: "minikube"
    registry: "public.ecr.aws/datadog"
  features:
    logCollection:
      enabled: true
      containerCollectAll: true

      

